#ifndef FILESYSTEM_H
#define FILESYSTEM_H

#include <string>
#include <cstdlib>
//#include "root_directory.h" // This is a configuration file generated by CMake.

class FileSystem
{
private:
	typedef std::string(*Builder) (const std::string& path);

public:
	static std::string getPath(const std::string& path)
	{
		static std::string(*pathBuilder)(std::string const&) = getPathBuilder();
		return (*pathBuilder)(path);
	}

private:

	static Builder getPathBuilder()
	{
		return &FileSystem::getPathRelativeBinary;
	}


	static std::string getPathRelativeBinary(const std::string& path)
	{
		return "../" + path;
	}


};

// FILESYSTEM_H
#endif
